import type { AiSummaryDto, FactDto } from "@/types/api";
import { formatDate, formatShortDate, isoDate } from "@/lib/format";
import { factValue, groupFacts } from "@/lib/content/facts";

function FactStatus({ fact }: { fact: FactDto }) {
  if (fact.status === "conflict") return <span className="fact__status fact__status--conflict">Sources disagree — not used</span>;
  const date = fact.verifiedAt ?? fact.observedAt;
  return (
    <span className={`fact__status fact__status--${fact.status}`}>
      {fact.status === "verified" ? "Verified " : "Checked "}
      <time dateTime={isoDate(date)}>{formatDate(date)}</time>
      {fact.status !== "verified" && " · not yet verified"}
      {fact.freshness.isStale && <span className="fact__stale"> · due for re-check</span>}
    </span>
  );
}

/**
 * "Sources & Verification" (spec §16–18): every fact with the source it rests
 * on and its own date, grouped by category.
 */
export function SourcesAndVerification({ facts, practiceNames = {} }: { facts: FactDto[]; practiceNames?: Record<string, string> }) {
  const groups = groupFacts(facts);
  if (groups.length === 0) return null;
  return (
    <section className="card" aria-labelledby="facts-heading" id="sources-and-verification">
      <h2 id="facts-heading" style={{ fontSize: "1.4rem" }}>
        Sources &amp; verification
      </h2>
      <p className="muted" style={{ fontSize: "0.9rem" }}>
        Each fact shows where it comes from and when it was last verified or checked. Official sources take precedence; a fact with
        conflicting sources is not used until it is resolved.
      </p>
      <div className="facts-panel">
        {groups.map((g) => (
          <div key={g.key} className="facts-panel__group">
            <h3 className="panel-title">{g.label}</h3>
            <ul>
              {g.facts.map((f) => (
                <li key={f.attribute} className="fact">
                  <span className="fact__label">{f.label}</span>
                  <span className="fact__value">{factValue(f, practiceNames)}</span>
                  <span className="fact__source">
                    {f.source.url && /^https?:\/\//.test(f.source.url) ? (
                      <a href={f.source.url} rel="nofollow noopener noreferrer" target="_blank">
                        {f.source.name ?? f.source.type ?? "Source"}
                      </a>
                    ) : (
                      (f.source.name ?? f.source.type ?? "Source")
                    )}
                    <span className="muted"> · {f.source.tierLabel}</span>
                  </span>
                  <FactStatus fact={f} />
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </section>
  );
}

/**
 * "At a glance" (spec §19): the answer-first summary generated by the CMS
 * from the profile's own facts, with each statement's status and date.
 */
export function AtAGlance({ summary, showText }: { summary: AiSummaryDto; showText: boolean }) {
  return (
    <section className="overview" aria-labelledby="glance-heading">
      <h2 id="glance-heading" className="panel-title" style={{ marginTop: 0 }}>
        At a glance
      </h2>
      {showText && <p style={{ margin: "0 0 0.75rem" }}>{summary.text}</p>}
      <dl className="glance">
        {summary.facts.map((f) => (
          <div key={f.key}>
            <dt>{f.label}</dt>
            <dd>
              {f.value}
              <span className={`glance__status glance__status--${f.status}`}>
                {f.status === "verified" ? "✓ verified" : f.status === "sourced" ? "sourced" : ""}
                {f.asOf && f.status !== "derived" ? ` ${formatShortDate(f.asOf)}` : ""}
              </span>
            </dd>
          </div>
        ))}
      </dl>
    </section>
  );
}
